//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApplicationDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ACCOUNTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_ACCOUNTS()
        {
            this.T_TRANSACTIONS = new HashSet<T_TRANSACTIONS>();
            this.T_TRANSACTIONS1 = new HashSet<T_TRANSACTIONS>();
        }
    
        public long AccountID { get; set; }
        public string AccountName { get; set; }
        public double AccountBalance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_TRANSACTIONS> T_TRANSACTIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_TRANSACTIONS> T_TRANSACTIONS1 { get; set; }
    }
}
