//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApplicationDemo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class T_TRANSACTIONS
    {
        public long FromAccountID { get; set; }
        public long ToAccountID { get; set; }
        public System.DateTime TransactionTime { get; set; }
        public double TransactionAmout { get; set; }
        public double FromAccountBalance { get; set; }
        public double ToAccountBalance { get; set; }
        public long ID { get; set; }
        [DisplayName ("AA")]
        public virtual T_ACCOUNTS T_ACCOUNTS { get; set; }
        public virtual T_ACCOUNTS T_ACCOUNTS1 { get; set; }
    }

    
}
